### ISSUE TITLE
[BUG]: chemistry search Timeout 'Substructure Search'

### ISSUE THREAD

**Issue by dellabiancial** [rspace-os/rspace-web#121]
**Describe the bug**
Chemistry Search -> enter some random drawing -> Click on 'Substructure' -> Click on Search

**Expected behavior**
List of Documents containing that drawing or part of it

**Screenshots**
![Screenshot 2024-09-19 134315](https://github.com/user-attachments/assets/85e23191-a9e8-42b6-a50f-38c525f26c03)

**Comment by tilorspace** [comment]
@dellabiancial thanks for reporting. I'm also closing this for now, since it's related to a non-open source component.
