### ISSUE TITLE
[BUG] Chemistry cdx file upload IOException

### ISSUE THREAD

**Issue by dellabiancial** [rspace-os/rspace-web#122]
**Describe the bug**
IOException when uploading a cdx file

**To Reproduce**
upload the file available on SURFFileSender. File sent via email to Matthias

**Comment by dellabiancial** [comment]
![Screenshot 2024-09-19 135807](https://github.com/user-attachments/assets/b2d1d1c1-e503-49ca-94d0-b64922f69e19)

**Comment by mKowalski256** [comment]
I received the KE196.cdx file, thank you. Saying that chemistry module is not a part of open-sourced RSpace platform, so this should be reported to support@researchspace.com. @tilorspace ?

**Comment by tuxRamon** [comment]
Yes, things like this should go to @support instead

**Comment by dellabiancial** [comment]
I opened this ticket long time but not much has been done due to ChemAxon integration. You can keep this report in mind when developing the new Chemistry feature ;-)

**Comment by tilorspace** [comment]
@dellabiancial thanks for reminding us. We'll keep the file for benchmarking any improvements we provide around chemistry in the open source project. I'll will close this ticket for now.
