### ISSUE TITLE
[RFC] : allow columns resize in the USERS' tab

### ISSUE THREAD

**Issue by dellabiancial** [rspace-os/rspace-web#126]
currently it is not possible to resize the columns in the USERS' menu. This makes it difficult to read the metadata.

See screenshots: 
![users column size](https://github.com/user-attachments/assets/ac243c53-85f8-4220-a68f-5886160f8286)

It would be useful to be able to read the values entirely when necessary

**Comment by rlamacraft** [comment]
Hi, this is already scheduled for inclusion in the next release (2.3.0), [as implemented by commit 47114a58f814a5da720812a374642d11c5bf05cb](https://github.com/rspace-os/rspace-web/commit/47114a58f814a5da720812a374642d11c5bf05cb). As such, I'm closing as done
