### ISSUE TITLE
Hardware requirements 

### ISSUE THREAD

**Issue by ll4strw** [rspace-os/rspace-web#27]
Would it be possible to add a doc section that mentions minimal hardware requirements to run RSpace please? I cannot seem to find this info unless I am mistaken.

**Comment by mKowalski256** [comment]
Yes makes sense, I've added the section to GettingStarted.md with [4ec2a21fcc77 commit](https://github.com/ResearchSpace-ELN/rspace-web/commit/4ec2a21fcc779270b199564ba0733ddeaa7c9dd5). Updated docs will be part of 2.0.0 release.
