### ISSUE TITLE
ServiceLoggerAspct logs unnecessary info

### ISSUE THREAD

**Issue by ll4strw** [rspace-os/rspace-web#42]
Dear RSpace Team,

when logging in to an external disk via 
https://github.com/rspace-os/rspace-web/blob/1de072f022fa43c7e7d22098640149ee5068fc4d/src/main/java/com/researchspace/service/NfsManager.java#L53-L59

then the following logging function

https://github.com/rspace-os/rspace-web/blob/1de072f022fa43c7e7d22098640149ee5068fc4d/src/main/java/com/researchspace/webapp/controller/ServiceLoggerAspct.java#L103-L105

results in, for instance, nfs credentials to be logged unnecessarily.

**Comment by mKowalski256** [comment]
Thank you for raising the issue, the logging should be fixed now with [commit 228b05c](https://github.com/rspace-os/rspace-web/commit/228b05cc28608d008fee4d5005a3907fdef05550).
