### ISSUE TITLE
[BUG] When sysadmin.delete.user is set to false, the delete button in the System page is NOT grayed out

### ISSUE THREAD

**Issue by tuxRamon** [rspace-os/rspace-web#46]
**Describe the bug**
Even though sysadmin.delete.user=false is set in deployment.properties, in the System page (once selecting a user and clicking the Actions button), the delete button for a user is clickable and not grayed out.

Furthermore, if the button is clicked, the page displays a green success message that the user has been deleted, when in fact the user has not been deleted.

**Expected behavior**
If sysadmin.delete.user=false in deployment.properties, the delete button should be grayed out, not allowing a user to click on the button.

**Comment by rlamacraft** [comment]
PR open #51
