### ISSUE TITLE
Deployment properties set through command line not honored

### ISSUE THREAD

**Issue by ll4strw** [rspace-os/rspace-web#63]
I am instructing RSpace v2.0.0 to use a different database than the default `rspace` by launching it with jetty using

```
RS_FILE_BASE=/home/leonardo/RSPACE/rspace_file_store mvn clean jetty:run \
-Denvironment=drop-recreate-db -DRS.devlogLevel=INFO \
-Dspring.profiles.active=run -Dliquibase.context=dev-test \
-DgenerateReactDist -Dlog4j2.configurationFile=log4j2-dev.xml \
-Djdbc.url=jdbc:mysql://localhost:3306/rspace_vanilla
```
I would expect from option `-Djdbc.url=jdbc:mysql://localhost:3306/rspace_vanilla` that an existing database named `rspace` would be left untouched, instead it is dropped and recreated where as the new database `rspace_vanilla` ends up containing only the following tables
```
+--------------------------+
| Tables_in_rspace_vanilla |
+--------------------------+
| DATABASECHANGELOG        |
| DATABASECHANGELOGLOCK    |
+--------------------------+

```
Eventually the building and launch process fails with error 
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'rspace_vanilla.roles' doesn't exist
```
Are perhaps options `-Denvironment=drop-recreate-db` and `-Djdbc.url=jdbc:mysql://localhost:3306/rspace_vanilla` incompatible? Or is their appearance order important? Thanks.

**Comment by rs-fraser** [comment]
@ll4strw I have updated the documentation in this PR https://github.com/rspace-os/rspace-web/pull/86 to explain an additional deployment property required to use a different database name.

In your case above, you would need to add (in addition to the existing params) `-Djdbc.db=rspace_vanilla`.

Let me know if you have any issues. More info here: https://github.com/rspace-os/rspace-web/blob/main/DevDocs/DeveloperNotes/GettingStarted/GettingStarted.md#set-deployment-properties-through-command-line

**Comment by rs-fraser** [comment]
@ll4strw apologies, there's an additional param also required `-Djdbc.db.maven=rspace_vanilla` which should work for you. I've update the [docs](https://github.com/rspace-os/rspace-web/blob/main/DevDocs/DeveloperNotes/GettingStarted/GettingStarted.md#set-deployment-properties-through-command-line) as well.

I'll create an internal ticket too to see if we can simplify these params as we are repeating information and it's quite confusing.
