### ISSUE TITLE
Initial db setup

### ISSUE THREAD

**Issue by ll4strw** [rspace-os/rspace-web#7]
If I set up my RSpace database for the first time with 
```
CREATE USER 'rspacedbuser'@'localhost' IDENTIFIED BY 'rspacedbpwd';
CREATE DATABASE rspace collate 'utf8mb4_unicode_ci';
GRANT ALL ON rspace.* TO 'rspacedbuser'@'localhost';
```
then all `mvn clean test .....` attempts fail with a db authentication error for user `rspacedbuser'@'127.0.0.1'`.

Shouldn't perhaps the docs instruct to create a ` 'rspacedbuser'@'127.0.0.1' ` user instead?
```
CREATE USER 'rspacedbuser'@'127.0.0.1' IDENTIFIED BY 'rspacedbpwd'; and
GRANT ALL ON rspace.* TO 'rspacedbuser'@'127.0.0.1';
```

**Comment by mKowalski256** [comment]
Thank you, addressed in [4ec2a21fcc77 commit](https://github.com/ResearchSpace-ELN/rspace-web/commit/4ec2a21fcc779270b199564ba0733ddeaa7c9dd5), updated docs will be part of 2.0.0 release.
